### ISSUE TITLE
Add support for importing from `ember-cli-htmlbars-inline-precompile`

### ISSUE THREAD

**Issue by rwjblue** [ember-codemods/ember-cli-htmlbars-inline-precompile-codemod#4]
With `ember-cli-htmlbars-inline-precompile` folks could import from _either_ `htmlbars-inline-precompile` or `ember-cli-htmlbars-inline-precompile`. We should ensure that this codemod updates both/either.

### Standard local name

Input:

```js
import hbs from 'ember-cli-htmlbars-inline-precompile';
```

Output:

```js
import { hbs } from 'ember-cli-htmlbars';
```

---

### Non-standard local name

Input:

```js
import h from 'ember-cli-htmlbars-inline-precompile';
```

Output:

```js
import { hbs as h } from 'ember-cli-htmlbars';
```

### Having both imports

(sadly, yes, I have seen this "in the wild")

Input:

```js
import hbs from 'ember-cli-htmlbars-inline-precompile';
import h from 'htmlbars-inline-precompile';
```

Output:

```js
import { hbs } from 'ember-cli-htmlbars';
import { hbs as h } from 'ember-cli-htmlbars';
```

**Comment by jeannettetang** [comment]
For having both imports, can it look more like this?

```
import { hbs as h, hbs } from 'ember-cli-htmlbars';
```

**Comment by rwjblue** [comment]
To be honest, I don’t know if you are allowed to import the same thing twice in the same import statement. We should test it out! 

If it works, yes we should absolutely emit a single statement.

**Comment by jeannettetang** [comment]
Looks like it does not work. Separate lines it is! 👍
